name: Release
run-name: Release ${{ github.actor }}
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 30
          fetch-tags: true
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: test
        run: |
          go vet ./...
          go test ./...
      - name: Build dist
        run: |
          bash -x ./release.sh
          ./dist/go2jail-linux-amd64 -version
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*
